services:
  rss-it:
    image: gucheen/rss-it:latest
    container_name: rss-it
    restart: always
    ports:
      - '3002:3000'
    volumes:
      - ./config.json:/usr/src/app/config.json
    labels:
      com.centurylinklabs.watchtower.enable: false
